public enum CampaignIssue {
    NO_FOCUS,
    HEALTHCARE,
    GUN_CONTROL,
    CIVIL_RIGHTS,
    CLIMATE_CHANGE,
    EDUCATION,
    RENEWABLE_ENERGY,
    TAX_REFORM,
    IMMIGRATION,
    THE_ECONOMY,
}
